### ISSUE TITLE
Mocking camera/Mic access is not working on safari

### ISSUE THREAD

**Issue by pawanamigo** [DevExpress/testcafe-examples#69]
I am unable to mock Camera/Mic access permissions on Safari when running my tests even after passing the "--use-fake-ui-for-media-stream" flag. 
However this is working fine on Chrome. Is there anything that I am missing. Our applications are video recording applications and needs Camera/Mic access. 

I am blocked on running tests on Safari. Any help is appreciated.

**Comment by miherlosev** [comment]
Hi @pawanamigo

Safari doesn't allow mocking camera/microphone access using the command-line flag, such as Google Chrome. Try to find alternative ways.
