### ISSUE TITLE
Provide a way to delay tests until a tested app can respond to a request

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe-examples#71]
### What is your Test Scenario?
Start an app that takes some time to start up and respond to the first HTTP request via the `--app` options.

### What are you suggesting?
Allow delaying test execution until an app can respond to an HTTP request, similar to [wait-on](https://www.npmjs.com/package/wait-on).

### Example
*TODO*: Use the `testRun.before` global hook to wait until the server is live.

Call `wait-on` API in the `fixture.before` hook:

```js
import waitOn from 'wait-on';

fixture`Fixture`
    .before(async () => {
        await waitOn({ resources: ['http://example.com'] });
    });
```

**Comment by Artem-Babich** [comment]
We decided not to implement this functionality. You can use the simple workaround described above. Feel free to reopen this issue and share appropriate details if this workaround is not suitable for you.
